image: $HELM_REGISTRY_IMAGE:$HELM_REGISTRY_VERSION

variables:
  REGISTRY: quay.io
  REGISTRY_USER: your_org # we set this to override to samsung_cnct in gitlab Group Variables
  CHART_NAME: vault
  PUBCHART_NAME: vault-chart
  ROBOT_ACCOUNT: chartvaultrw
  HELM_REGISTRY_IMAGE: quay.io/samsung_cnct/helm-registry-agent
  HELM_REGISTRY_VERSION: v0.7.4-helm_2.6
  KUBECTL_VERSION: v1.9.2

stages:
  - build
  - test
  - publish

before_script:
  - helm init --client-only
  - helm registry login -u ${REGISTRY_USER}+${ROBOT_ACCOUNT} -p ${REGISTRY_PASSWORD} ${REGISTRY}
  - export PROJECT_NAME=${CHART_NAME}
  - export CHART_VER=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')
  - export CHART_REL=$(git rev-list --count v${CHART_VER}..HEAD 2>/dev/null)

build_chart:
  stage: build
  only:
    - tags
    - branches
  artifacts: 
    paths:
      - ${CHART_NAME}
  script:
    - build/build.sh

helm_test:
  stage: test
  only:
    - tags
    - branches
  variables:
    ETCD_GIT_REPO: https://github.com/samsung-cnct/chart-vault-etcd.git
    ETCD_GIT_FOLDER: etcd-repo
    NAMESPACE: ${CHART_NAME}-test-${CI_PIPELINE_ID}
    RELEASE: ${CHART_NAME}-${CI_PIPELINE_ID}
    GEN_NAMESPACE: ${CHART_NAME}-test-${CI_PIPELINE_ID}
    GEN_STATEFULSET_NAME: etcd-vault
    GEN_STATEFULSET_NAME_VAULT: ${CHART_NAME}-${CI_PIPELINE_ID}
  script:
    - test/test.sh
  after_script:
    - test/cleanup.sh

helm_publish_alpha:
  stage: publish
  only:
    - master
  script:
    - cd ${CHART_NAME} && helm registry push ${REGISTRY}/${REGISTRY_USER}/${PUBCHART_NAME} -c alpha

helm_publish_tag:
  stage: publish
  only:
    - /v[0-9]+\.[0-9]+(\.[0-9]+[a-z]?)?/
  script:
    - cd ${CHART_NAME} && helm registry push ${REGISTRY}/${REGISTRY_USER}/${PUBCHART_NAME} -c stable