---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault.access" . }}
  labels:
    app: {{ template "vault.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - name: access
      protocol: TCP
      {{- if .Values.vault.tls.enabled }}
      port: 443
      targetPort: {{ .Values.vault.listenerPort }}
      {{- else }}
      port: 80
      targetPort: {{ .Values.vault.listenerPort }}
      {{- end }}
  selector:
    app: {{ template "vault.name" . }}