---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault.name" . }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{ template "vault.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - name: clusterlistener
      protocol: TCP
      port: {{ .Values.vault.clusterListenerPort }}
    - name: listener
      protocol: TCP
      {{- if .Values.vault.tls.enabled }}
      port: 443
      targetPort: {{ .Values.vault.listenerPort }}
      {{- else }}
      port: 80
      targetPort: {{ .Values.vault.listenerPort }}
      {{- end }}
  clusterIP: None
  selector:
    app: {{ template "vault.name" . }}
