---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault.name" . }}
  labels:
    app: {{ template "vault.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - name: clusterlistener
      protocol: TCP
      port: {{ .Values.vault.clusterListenerPort }}
    - name: listener
      protocol: TCP
      port: {{ .Values.vault.listenerPort }}
  clusterIP: None
  selector:
    app: {{ template "vault.name" . }}
