---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-init-run
  labels:
    app: {{ template "vault.name" . }}-initscript
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  init-vault.sh: |-
{{ .Files.Get "init-vault.sh" | indent 4 }}
