---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "vault.name" . }}-initjob
  labels:
    app: initjob
spec:
  template:
    metadata:
      name: {{ template "vault.fullname" . }}-initscript
    spec:
      serviceAccountName: {{ template "vault.fullname" . }}-secret-writer
      containers:
      {{ include "containerInitVault" . | indent 6 }}
      volumes:
      - name: initpayload
        configMap:
          name: vault-init-payload
      - name: initscript
        configMap:
          name: vault-init-run
      {{- if .Values.vault.tls.enabled }}
      - name: vault-tls
        secret:
          secretName: {{ .Values.vault.tls.secret.name }}
      {{- end }}
      restartPolicy: Never
  backoffLimit: {{ .Values.vault.initBackoff }}
  activeDeadlineSeconds: {{ .Values.vault.initDeadline }}
