---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vault.fullname" . }}-secret-writer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "vault.fullname" . }}-secret-writer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "vault.fullname" . }}-secret-writer
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "vault.fullname" . }}-secret-writer
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "vault.fullname" . }}-secret-writer
  apiGroup: rbac.authorization.k8s.io

