---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    app: {{ template "vault.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.vault.component }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - name: {{ template "vault.fullname" . }}
      protocol: TCP
{{- if .Values.vault.enableTLS }}
      port: 443
      targetPort: 443
{{- else }}
      port: 80
      targetPort: 80
{{- end }}
  selector:
    app: {{.Release.Name}}
