---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "vault.name" . }}
  labels:
    app: {{ template "vault.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ template "vault.name" . }}
  replicas: {{ .Values.vault.replicas }}
  selector:
    matchLabels:
      app: {{ template "vault.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "vault.name" . }}
    spec:
      nodeSelector:
        nodepool: clusterNodes
      containers:
      {{ include "containerVault" . | indent 6 }}
      initContainers:
      {{ include "containerWaitEtcd" . | indent 6 }}
      volumes:
      {{- if .Values.vault.tls.enabled }}
      - name: vault-tls-data
        secret:
          secretName: {{ .Values.vault.tls.secret.name }}
      {{- end }}
      - name: config
        configMap:
          name: {{ template "vault.name" . }}-run
      {{- if .Values.vault.etcdBackend.tls.enabled }}
      - name: etcd-tls
        secret:
          secretName: {{ .Values.vault.etcdBackend.tls.secret.name }}
      {{- end }}
{{- if .Values.vault.tolerations }}
      tolerations:
      {{- range .Values.vault.tolerations }}
      - key: {{ .key | default ("") }}
        value: {{ .value | default ("")}}
        operator: {{ .operator | default ("Equal") }}
        effect: {{ .effect  | default ("")}}
      {{- end }}
{{- end }}
{{- if .Values.vault.scheduling.affinity }}
{{- if .Values.vault.scheduling.affinity.node }}
{{- if .Values.vault.scheduling.affinity.node.labels }}
      affinity:
        nodeAffinity:
          {{ .Values.vault.scheduling.affinity.node.type }}:
            nodeSelectorTerms:
            - matchExpressions:
                {{- range .Values.vault.scheduling.affinity.node.labels }}
                - key: {{ .key }}
                  operator: {{ .operator }}
                  values:
                  {{- range .values }}
                  - {{ . }}
                  {{- end }}
                {{- end }}
{{- end }}
{{- end }}
{{- end }}