---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "vault.name" . }}-secret-rw
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "vault.name" . }}-secret-rw
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "vault.name" . }}-secret-rw
  apiGroup: rbac.authorization.k8s.io