---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "vault.name" . }}-secret-rw
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ .Values.vault.setup.masterSecret | default (include "vault.name" .) }}"]
  verbs: ["get"]