---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault.name" . }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{ template "vault.name" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - name: clusterlistener
      protocol: TCP
      port: {{ .Values.vault.clusterListenerPort }}
    - name: listener
      protocol: TCP
      port: {{ .Values.vault.listenerPort }}
  clusterIP: None
  selector:
    app: {{ template "vault.name" . }}
