---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "vault.name" . }}-init
spec:
  template:
    metadata:
      name: {{ template "vault.name" . }}-init
    spec:
      serviceAccountName: {{ template "vault.name" . }}-secret-rw
      initContainers:
      {{- if .Values.vault.setup.init }}
      {{ include "containerInitVault" . | indent 6 }}  
      {{- end }}
      {{- if and .Values.vault.setup.unseal }}
      {{ include "containerUnsealVault" . | indent 6 }}  
      {{- end }}
      containers:
      {{ include "containerSetupVault" . | indent 6 }}  
      volumes:
      - name: config
        configMap:
          name: {{ template "vault.name" . }}-config
      {{- if .Values.vault.tls.enabled }}
      - name: vault-tls-data
        secret:
          secretName: {{ .Values.vault.tls.secret.name }}
      {{- end }}
      restartPolicy: Never
  backoffLimit: {{ .Values.vault.initBackoff }}
  activeDeadlineSeconds: {{ .Values.vault.initDeadline }}